# This workflow runs SDK related jobs for OpenMLDB
name: SDK

on:
  push:
    branches:
      - main
      - release_python_mac0.6.5
    paths-ignore:
      - "docs/**"
      - "demo/**"
      - "docker/**"
      - "image/**"
      - "release/**"
      - "tools/**"
      - "*.md"
    tags:
      - v*
  pull_request:
    paths-ignore:
      - "docs/**"
      - "demo/**"
      - "docker/**"
      - "image/**"
      - "release/**"
      - "tools/**"
      - "*.md"
  workflow_dispatch:

env:
  GIT_SUBMODULE_STRATEGY: recursive
  NPROC: 2 # default Parallel build number for GitHub's Linux runner
  EXAMPLES_ENABLE: OFF # turn off hybridse's example code
  HYBRIDSE_TESTING_ENABLE: OFF # turn off hybridse's test code

jobs:
  java-sdk:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/4paradigm/hybridsql:latest
    env:
      SQL_JAVASDK_ENABLE: ON
      OPENMLDB_BUILD_TARGET: "cp_native_so openmldb"
      MAVEN_OPTS: -Duser.home=/github/home
      SPARK_HOME: /tmp/spark/
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "8"
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_TOKEN
          gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase

      - name: Import GPG key
        id: import_gpg
        if: github.event_name == 'push'
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('java/**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: prepare release
        if: github.event_name == 'push'
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          VERSION=${VERSION#v}
          ./java/prepare_release.sh "$VERSION"

  java-sdk-mac:
    # mac job for java sdk. steps are almost same with job 'java-sdk'
    # except mvn deploy won't target all modules, just hybridse-native & openmldb-native
    # the job only run on tag push or manual workflow dispatch due to no test runs
    runs-on: macos-latest
    needs:
      - java-sdk
    if: github.event_name == 'push'
    env:
      SQL_JAVASDK_ENABLE: ON
      OPENMLDB_BUILD_TARGET: "cp_native_so openmldb"
      NPROC: 3
    steps:
      - uses: actions/checkout@v3

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('java/**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache thirdparty
        uses: actions/cache@v3
        with:
          path: |
            .deps/
            thirdsrc
          key: ${{ runner.os }}-thirdparty-${{ hashFiles('third-party/**/CMakeLists.txt', 'third-party/**/*.cmake', 'third-party/**/*.sh') }}

  python-sdk:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/4paradigm/hybridsql:latest
    env:
      SQL_PYSDK_ENABLE: ON
      OPENMLDB_BUILD_TARGET: "cp_python_sdk_so openmldb"
    steps:
      - uses: actions/checkout@v2

      - name: prepare release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          VERSION=${VERSION#v}
          bash steps/prepare_release.sh "$VERSION"

      - name: build pysdk and sqlalchemy
        run: |
          make build

      - name: prepare python deps
        run: |
          python3 -m easy_install pip
          pip install setuptools wheel twine
          yum install -y net-tools

  python-sdk-mac:
    runs-on: macos-12
    if: github.event_name == 'push'
    env:
      SQL_PYSDK_ENABLE: ON
      OPENMLDB_BUILD_TARGET: "cp_python_sdk_so openmldb"
    steps:
      - uses: actions/checkout@v3

      - name: prepare release
        #if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          VERSION="v0.6.5"
          VERSION=${VERSION#v}
          bash steps/prepare_release.sh "$VERSION"

      - name: build pysdk and sqlalchemy
        run: |
          make build

      - name: prepare python deps
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python3 get-pip.py
          python3 -m pip install setuptools wheel twine

      - name: test sqlalchemy
        run: |
          bash steps/test_python.sh

      - name: upload python ut results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: mac-ut-result-python-${{ github.sha }}
          path: |
            python/openmldb_sdk/openmldb/tests/pytest.xml

      - name: upload to pypi
        #if: >
        #  github.repository == '4paradigm/OpenMLDB' && startsWith(github.ref, 'refs/tags/v')
        run: |
          PATH=$PATH:/Library/Frameworks/Python.framework/Versions/3.11/bin
          cp python/openmldb_sdk/dist/openmldb*.whl .
          cp python/openmldb_tool/dist/openmldb*.whl .
          twine upload openmldb-*.whl
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

  go-sdk:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/4paradigm/hybridsql:latest
    env:
      OPENMLDB_BUILD_TARGET: "openmldb"
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: build openmldb
        run: make build install

      - name: start server
        run: ./openmldb/bin/start-standalone.sh

      - name: init test database
        env:
          OPENMLDB_NS_HOST: 127.0.0.1
          OPENMLDB_NS_PORT: 6527
        run: |
          echo "CREATE DATABASE test_db;" | ./openmldb/bin/openmldb --host=$OPENMLDB_NS_HOST --port=$OPENMLDB_NS_PORT

      - name: go test
        env:
          OPENMLDB_APISERVER_HOST: 127.0.0.1
          OPENMLDB_APISERVER_PORT: 8080
        working-directory: go
        run: go test ./... -race -covermode=atomic -coverprofile=coverage.out

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          name: coverage-go
          files: go/coverage.out
          fail_ci_if_error: true
          verbose: true

      - name: stop server
        run: ./openmldb/bin/stop-standalone.sh

  publish-test-results:
    needs: ["java-sdk", "python-sdk", "go-sdk"]
    # the action will only run on 4paradigm/OpenMLDB's context, not for fork repo or dependabot
    if: >
      always() && github.event_name == 'push' || (
      github.event.pull_request.head.repo.full_name == github.repository &&
      github.event.sender.login != 'dependabot[bot]' )
    name: Publish SDK Test Results
    uses: ./.github/workflows/publish-test-results-action.yml
    with:
      files: |
        linux-ut-result-*/**/*.xml
        mac-ut-result-*/**/*.xml
      check_name: SDK Test Report
      comment_title: SDK Test Report
